version: '3.9'

services:
  nginx-pm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  gogs:
    image: gogs/gogs:latest
    ports:
      - "10022:22"
      - "3000:3000"
    environment:
      - "RUN_CROND=true"
    volumes:
      - "gogs-data:/data"
  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    env_file:
      - postgresql.env

volumes:
  db-data:
    driver: local
  gogs-data:
    driver: local
